
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Home Tacos", "Business", 1000, "2017-11-06", "2017-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sick Album", "Music", 1000,"2017-11-06", "2017-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Honey Moon Trippin'", "Expierence", 1000, "2017-11-06", "2017-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bootcamp Fund", "Education", 1000, "2017-11-06", "2017-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Walking Dogs", "Business", 1000, "2017-11-06", "2017-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Home Tacos", "Business", 1000, "2017-11-06", "2017-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Home Tacos", "Business", 1000, "2017-11-06", "2017-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Home Tacos", "Business", 1000, "2017-11-06", "2017-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Home Tacos", "Business", 1000, "2017-11-06", "2017-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Home Tacos", "Business", 1000, "2017-11-06", "2017-12-31");

INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);
INSERT INTO users (name, age) VALUES ("Seth Barden", 31);

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 1);
